<?php

return [
    'default' => 'zen',

    'themes' => [
        'zen' => [
            'label' => 'Zen',
            'description' => 'Theme principal issu du mockup design system BouclePro : bleu profond, violet Loop, vert progression et surfaces claires.',
            'tokens' => [
                'page' => '#F3FAF4',
                'surface' => '#F3FAF4',
                'surface-soft' => '#DDE3F0',
                'panel' => '#FFFFFF',
                'primary' => '#0B4DFF',
                'primary-deep' => '#1237C9',
                'accent' => '#8A2CFF',
                'progress' => '#7DFF00',
                'validation' => '#FFC700',
                'info' => '#C7F2FF',
                'warning' => '#FFB24D',
                'text' => '#101010',
                'muted' => '#667085',
                'disabled' => '#9AA3B0',
                'border' => '#DDE3F0',
                'card-loop' => '#0B4DFF',
                'card-exchange' => '#8A2CFF',
                'card-directory' => '#7DFF00',
                'card-news' => '#FFC700',
                'card-welcome' => '#FFFFFF',
            ],
            'dark' => [
                'page' => '#06143A',
                'surface' => '#0A2058',
                'surface-soft' => '#102B72',
                'panel' => '#050F2C',
                'primary' => '#527DFF',
                'primary-deep' => '#0B4DFF',
                'accent' => '#B13DFF',
                'progress' => '#73F000',
                'validation' => '#FFC700',
                'info' => '#C7F2FF',
                'warning' => '#FFB24D',
                'text' => '#F8FAFC',
                'muted' => '#C7D2FE',
                'disabled' => '#9AA3B0',
                'border' => '#24427F',
                'card-loop' => '#527DFF',
                'card-exchange' => '#B13DFF',
                'card-directory' => '#73F000',
                'card-news' => '#FFC700',
                'card-welcome' => '#050F2C',
            ],
        ],

        'sable' => [
            'label' => 'Sable',
            'description' => 'Theme alternatif chaleureux, sobre et mineral.',
            'tokens' => [
                'page' => '#EFEAE2',
                'surface' => '#FFFAF0',
                'surface-soft' => '#F5EFE3',
                'panel' => '#FFFFFF',
                'primary' => '#047857',
                'primary-deep' => '#065F46',
                'accent' => '#C084FC',
                'progress' => '#10B981',
                'validation' => '#F59E0B',
                'info' => '#DBEAFE',
                'warning' => '#FED7AA',
                'text' => '#292524',
                'muted' => '#78716C',
                'disabled' => '#A8A29E',
                'border' => '#E7E0D3',
                'card-loop' => '#047857',
                'card-exchange' => '#C084FC',
                'card-directory' => '#10B981',
                'card-news' => '#F59E0B',
                'card-welcome' => '#FFFFFF',
            ],
            'dark' => [
                'page' => '#0F172A',
                'surface' => '#111827',
                'surface-soft' => '#1F2937',
                'panel' => '#020617',
                'primary' => '#34D399',
                'primary-deep' => '#059669',
                'accent' => '#A78BFA',
                'progress' => '#4ADE80',
                'validation' => '#FBBF24',
                'info' => '#1E3A5F',
                'warning' => '#92400E',
                'text' => '#F8FAFC',
                'muted' => '#CBD5E1',
                'disabled' => '#64748B',
                'border' => '#334155',
                'card-loop' => '#34D399',
                'card-exchange' => '#A78BFA',
                'card-directory' => '#4ADE80',
                'card-news' => '#FBBF24',
                'card-welcome' => '#020617',
            ],
        ],

        'sea' => [
            'label' => 'Sea',
            'description' => 'Design system bleu BouclePro : energie, progression et validation visibles.',
            'tokens' => [
                'page' => '#E8EDF5',
                'surface' => '#F3FAF4',
                'surface-soft' => '#E6ECF7',
                'panel' => '#FFFFFF',
                'primary' => '#0B4DFF',
                'primary-deep' => '#1237C9',
                'accent' => '#8A2CFF',
                'progress' => '#7DFF00',
                'validation' => '#FFC700',
                'info' => '#C7F2FF',
                'warning' => '#FFB24D',
                'text' => '#101010',
                'muted' => '#667085',
                'disabled' => '#9AA3B0',
                'border' => '#DDE3F0',
                'card-loop' => '#0B4DFF',
                'card-exchange' => '#8A2CFF',
                'card-directory' => '#7DFF00',
                'card-news' => '#FFC700',
                'card-welcome' => '#FFFFFF',
            ],
            'dark' => [
                'page' => '#06143A',
                'surface' => '#0A2058',
                'surface-soft' => '#102B72',
                'panel' => '#050F2C',
                'primary' => '#527DFF',
                'primary-deep' => '#0B4DFF',
                'accent' => '#B13DFF',
                'progress' => '#73F000',
                'validation' => '#FFC700',
                'info' => '#C7F2FF',
                'warning' => '#FFB24D',
                'text' => '#F8FAFC',
                'muted' => '#C7D2FE',
                'disabled' => '#9AA3B0',
                'border' => '#24427F',
                'card-loop' => '#527DFF',
                'card-exchange' => '#B13DFF',
                'card-directory' => '#73F000',
                'card-news' => '#FFC700',
                'card-welcome' => '#050F2C',
            ],
        ],

        'inside' => [
            'label' => 'Inside',
            'description' => 'Theme bleu initial conserve pour compatibilite avec les premiers essais.',
            'tokens' => [
                'page' => '#E8EDF5',
                'surface' => '#F3FAF4',
                'surface-soft' => '#E6ECF7',
                'panel' => '#FFFFFF',
                'primary' => '#0B4DFF',
                'primary-deep' => '#1237C9',
                'accent' => '#8A2CFF',
                'progress' => '#7DFF00',
                'validation' => '#FFC700',
                'info' => '#C7F2FF',
                'warning' => '#FFB24D',
                'text' => '#1C1C1E',
                'muted' => '#667085',
                'disabled' => '#9AA3B0',
                'border' => '#DDE3F0',
                'card-loop' => '#0B4DFF',
                'card-exchange' => '#8A2CFF',
                'card-directory' => '#7DFF00',
                'card-news' => '#FFC700',
                'card-welcome' => '#FFFFFF',
            ],
            'dark' => [
                'page' => '#071338',
                'surface' => '#0B1F55',
                'surface-soft' => '#10276A',
                'panel' => '#06102F',
                'primary' => '#6C95FF',
                'primary-deep' => '#0B4DFF',
                'accent' => '#B13DFF',
                'progress' => '#73F000',
                'validation' => '#FFC700',
                'info' => '#C7F2FF',
                'warning' => '#FFB24D',
                'text' => '#F8FAFC',
                'muted' => '#C7D2FE',
                'disabled' => '#9AA3B0',
                'border' => '#24427F',
                'card-loop' => '#6C95FF',
                'card-exchange' => '#B13DFF',
                'card-directory' => '#73F000',
                'card-news' => '#FFC700',
                'card-welcome' => '#06102F',
            ],
        ],
    ],
];
